"use client";

import Image from "next/image";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useEffect, useMemo, useState } from "react";
import type { ChangeEvent, FormEvent } from "react";
import { uploadApi } from "../../../services/upload";
import { useAppDispatch, useAppSelector } from "../../../hooks/useRedux";
import { createChild, updateChild } from "../../../store/slices/childSlice";
import { validateChildDateOfBirth } from "../../../utils/validation";

type ChildGender = "MALE" | "FEMALE" | "OTHER";
type Step = 1 | 2;

const baseInput =
  "mt-2 h-[58px] w-full rounded-2xl border border-[#0a3d62] bg-[#f5f5f5]/85 px-4 text-sm text-[#0a3d62] outline-none transition placeholder:text-[#9aa9b4] focus:border-[#0071d7] focus:ring-4 focus:ring-[#0071d7]/15";

const baseTextArea =
  "mt-2 min-h-[144px] w-full rounded-2xl border border-[#0a3d62] bg-[#f5f5f5]/85 px-4 py-4 text-sm text-[#0a3d62] outline-none transition placeholder:text-[#9aa9b4] focus:border-[#0071d7] focus:ring-4 focus:ring-[#0071d7]/15";

const compactTextArea =
  "mt-2 min-h-[116px] w-full rounded-2xl border border-[#0a3d62] bg-[#f5f5f5]/85 px-4 py-4 text-sm text-[#0a3d62] outline-none placeholder:text-[#9aa9b4] focus:border-[#0071d7] focus:ring-4 focus:ring-[#0071d7]/15";

function yearsFromDob(dateOfBirth: string) {
  if (!dateOfBirth) return "";
  const dob = new Date(dateOfBirth);
  const today = new Date();
  let age = today.getFullYear() - dob.getFullYear();
  const monthDelta = today.getMonth() - dob.getMonth();
  if (monthDelta < 0 || (monthDelta === 0 && today.getDate() < dob.getDate())) age -= 1;
  return Number.isFinite(age) && age >= 0 ? `${age} years` : "";
}

function requiredComplete(values: string[]) {
  return values.every((value) => value.trim().length > 0);
}

function StepIndicator({ step }: { step: Step }) {
  return (
    <div className="flex justify-center gap-5 pt-3" aria-label={`Step ${step} of 2`}>
      <span className={`h-[2px] w-16 rounded-full ${step === 1 ? "bg-[#0a3d62]" : "bg-[#b5d3ee]"}`} />
      <span className={`h-[2px] w-16 rounded-full ${step === 2 ? "bg-[#0a3d62]" : "bg-[#b5d3ee]"}`} />
    </div>
  );
}

function FieldLabel({ children, required = false }: { children: string; required?: boolean }) {
  return (
    <label className="block text-sm font-medium text-[#111]">
      {children}
      {required && <span className="text-[#e53935]"> *</span>}
    </label>
  );
}

function CameraUploadIcon() {
  return (
    <svg aria-hidden="true" viewBox="0 0 64 64" className="h-16 w-16 text-[#0a3d62]">
      <path d="M17 24.5h8.4l3.8-5.5h11.6l3.8 5.5H50a6 6 0 0 1 6 6V47a6 6 0 0 1-6 6H17a6 6 0 0 1-6-6V30.5a6 6 0 0 1 6-6Z" fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="5" />
      <path d="M33.5 44a8 8 0 1 0 0-16 8 8 0 0 0 0 16Z" fill="none" stroke="currentColor" strokeWidth="5" />
      <path d="M49 12v12M43 18h12" fill="none" stroke="currentColor" strokeLinecap="round" strokeWidth="5" />
    </svg>
  );
}

function Toast({ message, tone }: { message: string; tone: "success" | "error" }) {
  return (
    <div
      className={`fixed right-8 top-8 z-30 max-w-2xl rounded-xl px-5 py-3 text-sm font-medium text-white shadow-lg ${
        tone === "success" ? "bg-[#2e7d32]" : "bg-[#ef4444]"
      }`}
    >
      {message}
    </div>
  );
}

export default function AddChildPage() {
  const router = useRouter();
  const dispatch = useAppDispatch();
  const { isAuthenticated } = useAppSelector((state) => state.auth);

  const [form, setForm] = useState({
    firstName: "",
    lastName: "",
    dateOfBirth: "",
    gender: "" as ChildGender | "",
    diagnosis: "",
    coExistingConditions: "",
    currentMedications: "",
    notes: "",
    supportMessage: "",
  });
  const [step, setStep] = useState<Step>(1);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [error, setError] = useState("");
  const [success, setSuccess] = useState("");
  const [pictureFile, setPictureFile] = useState<File | null>(null);
  const [picturePreview, setPicturePreview] = useState("");

  const age = useMemo(() => yearsFromDob(form.dateOfBirth), [form.dateOfBirth]);
  const childCode = useMemo(() => {
    if (!form.firstName && !form.lastName && !form.dateOfBirth) return "Autogenerated after selecting DOB";
    const prefix = `${form.firstName.slice(0, 2)}${form.lastName.slice(0, 2)}`.toUpperCase() || "NB";
    return `${prefix}${form.dateOfBirth.replaceAll("-", "").slice(2) || "RIDGE"}`;
  }, [form.dateOfBirth, form.firstName, form.lastName]);

  const canContinue = requiredComplete([form.firstName, form.lastName, form.dateOfBirth, form.gender]);
  const canSubmit = canContinue && requiredComplete([form.diagnosis, form.coExistingConditions, form.notes]);

  useEffect(() => {
    if (!isAuthenticated) router.push("/login");
  }, [isAuthenticated, router]);

  useEffect(() => {
    return () => {
      if (picturePreview) URL.revokeObjectURL(picturePreview);
    };
  }, [picturePreview]);

  function handleChange(event: ChangeEvent<HTMLInputElement | HTMLSelectElement | HTMLTextAreaElement>) {
    setForm((prev) => ({ ...prev, [event.target.name]: event.target.value }));
    if (error) setError("");
  }

  function handlePictureChange(event: ChangeEvent<HTMLInputElement>) {
    const file = event.target.files?.[0];
    if (!file) return;
    if (!file.type.startsWith("image/")) {
      setError("Please upload an image file for your child's picture.");
      return;
    }
    if (file.size > 5 * 1024 * 1024) {
      setError("Please upload an image smaller than 5MB.");
      return;
    }
    if (picturePreview) URL.revokeObjectURL(picturePreview);
    setPictureFile(file);
    setPicturePreview(URL.createObjectURL(file));
  }

  function goToStepTwo() {
    if (!canContinue) {
      setError("Something went wrong. Please resubmit and do check if all required fields are filled");
      return;
    }
    const dateValidationError = validateChildDateOfBirth(form.dateOfBirth);
    if (dateValidationError) {
      setError(dateValidationError);
      return;
    }
    setStep(2);
    setError("");
  }

  async function handleSubmit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    setError("");
    setSuccess("");

    if (!canSubmit) {
      setError("Something went wrong. Please resubmit and do check if all required fields are filled");
      return;
    }
    const dateValidationError = validateChildDateOfBirth(form.dateOfBirth);
    if (dateValidationError) {
      setError(dateValidationError);
      return;
    }

    try {
      setIsSubmitting(true);
      const result = await dispatch(
        createChild({
          firstName: form.firstName.trim(),
          lastName: form.lastName.trim(),
          dateOfBirth: new Date(form.dateOfBirth).toISOString(),
          gender: form.gender as ChildGender,
          diagnosis: form.diagnosis.trim(),
          coExistingConditions: form.coExistingConditions.trim() || undefined,
          currentMedications: form.currentMedications.trim() || undefined,
          notes: form.notes.trim(),
          supportMessage: form.supportMessage.trim() || undefined,
        }),
      );

      if (createChild.fulfilled.match(result)) {
        if (pictureFile) {
          const uploaded = await uploadApi.upload(pictureFile, result.payload.id);
          await dispatch(updateChild({ id: result.payload.id, data: { profileImage: uploaded.attachment.url } }));
        }
        setSuccess("Your child's information has been taken successfully. Kindly wait for our admin to assign you to a therapist");
        window.setTimeout(() => router.push("/dashboard"), 1100);
        return;
      }
    } catch {
      setError("Something went wrong. Please resubmit and do check if all required fields are filled");
    } finally {
      setIsSubmitting(false);
    }

    setError("Something went wrong. Please resubmit and do check if all required fields are filled");
  }

  return (
    <div className="relative min-h-screen overflow-hidden bg-[#fafafa]">
      <Image
        src="/design-assets/children-classroom.jpg"
        alt=""
        fill
        priority
        sizes="100vw"
        className="object-cover opacity-10"
      />
      <div className="absolute inset-0 bg-white/72" />

      {success && <Toast message={success} tone="success" />}
      {error && <Toast message={error} tone="error" />}

      <div className="relative z-10 mx-auto flex min-h-screen max-w-[1440px] flex-col px-8 py-10">
        <header className="flex items-start justify-between">
          <Link href="/dashboard" aria-label="Neuro Bridge Africa dashboard">
            <Image src="/design-assets/logo-transparent.png" alt="Neuro Bridge Africa" width={250} height={90} className="h-auto w-48" />
          </Link>
          <nav className="flex items-center gap-8 text-sm font-medium">
            <Link href="/dashboard" className="text-[#111] hover:text-[#0071d7]">Home</Link>
            <Link href="/about" className="text-[#111] hover:text-[#0071d7]">About Us</Link>
          </nav>
        </header>

        <main className="flex flex-1 flex-col justify-center py-8">
          <Link href={step === 1 ? "/dashboard" : "#"} onClick={(event) => {
            if (step === 2) {
              event.preventDefault();
              setStep(1);
            }
          }} className="mb-10 inline-flex w-fit items-center text-sm font-medium text-[#111] hover:text-[#0071d7]">
            &larr; {step === 1 ? "Go Back Home" : "Go to Step 1/2"}
          </Link>

          <form onSubmit={handleSubmit} className="mx-auto w-full max-w-[1080px]">
            <div className="mb-10 text-center">
              <h1 className="text-3xl font-semibold tracking-normal text-[#111]">Add Your Child&apos;s Profile Information</h1>
              <p className="mt-4 text-xl font-medium text-[#111]">
                {step === 1 ? "Step 1/2 - Core Child Profile Details" : "Step 2/2 - Medical & Developmental Information"}
              </p>
              <StepIndicator step={step} />
            </div>

            {step === 1 ? (
              <div className="grid gap-8 lg:grid-cols-[380px_1fr]">
                <label className="flex min-h-[526px] cursor-pointer flex-col items-center justify-center rounded-[28px] bg-[#b5d3ee] p-6 text-center text-[#0a3d62] transition hover:bg-[#a9cbea]">
                  <input type="file" accept="image/*" className="sr-only" onChange={handlePictureChange} />
                  {picturePreview ? (
                    <Image src={picturePreview} alt="Selected child profile" width={220} height={220} className="mb-8 h-52 w-52 rounded-full object-cover" unoptimized />
                  ) : (
                    <div className="mb-7 flex h-24 w-24 items-center justify-center">
                      <CameraUploadIcon />
                    </div>
                  )}
                  <span className="text-2xl font-semibold">Add Your Child&apos;s Picture here</span>
                </label>
                <section className="space-y-6">
                  <p className="text-sm text-[#111]">Fields marked as <span className="text-[#e53935]">*</span> is required</p>
                  <div className="grid gap-6 md:grid-cols-2">
                    <div>
                      <FieldLabel required>First Name</FieldLabel>
                      <input name="firstName" value={form.firstName} onChange={handleChange} placeholder="Enter your child's first name" className={baseInput} />
                    </div>
                    <div>
                      <FieldLabel required>Last Name</FieldLabel>
                      <input name="lastName" value={form.lastName} onChange={handleChange} placeholder="Enter your child's last name" className={baseInput} />
                    </div>
                    <div>
                      <FieldLabel required>Gender</FieldLabel>
                      <select name="gender" value={form.gender} onChange={handleChange} className={baseInput}>
                        <option value="">Select your child&apos;s gender</option>
                        <option value="MALE">Male</option>
                        <option value="FEMALE">Female</option>
                        <option value="OTHER">Other</option>
                      </select>
                    </div>
                    <div>
                      <FieldLabel required>Date Of Birth</FieldLabel>
                      <input name="dateOfBirth" type="date" value={form.dateOfBirth} onChange={handleChange} className={baseInput} />
                    </div>
                    <div>
                      <FieldLabel required>Your Child&apos;s Age</FieldLabel>
                      <input value={age || "Autogenerated after selecting DOB"} readOnly className={`${baseInput} cursor-not-allowed text-[#757575]`} />
                    </div>
                    <div>
                      <FieldLabel>Unique Child ID (Autogenerated)</FieldLabel>
                      <input value={childCode} readOnly className={`${baseInput} cursor-not-allowed text-[#757575]`} />
                    </div>
                  </div>
                  <div className="flex justify-end">
                    <button
                      type="button"
                      disabled={!canContinue}
                      onClick={goToStepTwo}
                      className="h-[60px] w-full rounded-2xl bg-[#0a3d62] px-8 text-base font-medium text-white transition hover:bg-[#0071d7] disabled:cursor-not-allowed disabled:bg-[#b5d3ee] md:w-auto md:min-w-[460px]"
                    >
                      {canContinue ? "Next" : "Submit"}
                    </button>
                  </div>
                </section>
              </div>
            ) : (
                <section className="mx-auto w-full max-w-[560px] space-y-6">
                  <p className="text-sm text-[#111]">Fields marked as <span className="text-[#e53935]">*</span> is required</p>
                  <div className="space-y-6">
                    <div>
                      <FieldLabel required>Child&apos;s Main Diagnosis</FieldLabel>
                      <input name="diagnosis" value={form.diagnosis} onChange={handleChange} placeholder="Eg. Autism, ADHD, Speech delay, etc" className={baseInput} />
                    </div>
                    <div>
                      <FieldLabel required>Co-existing conditions</FieldLabel>
                      <input name="coExistingConditions" value={form.coExistingConditions} onChange={handleChange} placeholder="Add any co-existing child health conditions" className={baseInput} />
                    </div>
                    <div>
                      <FieldLabel>Medications (If any)</FieldLabel>
                      <textarea
                        name="currentMedications"
                        value={form.currentMedications}
                        onChange={handleChange}
                        placeholder="Enter any medications your child is on"
                        className={compactTextArea}
                      />
                    </div>
                    <div>
                      <FieldLabel required>Developmental History Summary</FieldLabel>
                      <textarea
                        name="notes"
                        value={form.notes}
                        onChange={handleChange}
                        maxLength={1000}
                        placeholder="Maximum of 1000 characters"
                        className={compactTextArea}
                      />
                    </div>
                    <div>
                      <FieldLabel>Message</FieldLabel>
                      <textarea
                        name="supportMessage"
                        value={form.supportMessage}
                        onChange={handleChange}
                        placeholder="Hi Akosua, I'm Andrews and I have a problem with my account. Any help?"
                        className={baseTextArea}
                      />
                    </div>
                  </div>
                  <div className="flex justify-end">
                    <button
                      type="submit"
                      disabled={!canSubmit || isSubmitting}
                      className="h-[60px] w-full rounded-2xl bg-[#0a3d62] px-8 text-base font-medium text-white transition hover:bg-[#0071d7] disabled:cursor-not-allowed disabled:bg-[#b5d3ee]"
                    >
                      {isSubmitting ? "Submitting..." : "Submit"}
                    </button>
                  </div>
                </section>
              )}
          </form>
        </main>
      </div>
    </div>
  );
}
